config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    :registration => "users/registrations",
    :session => "users/sessions"
  }
  resources :tweets
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'tweets#index'
  post 'likes/:tweet_id', to: 'likes#create', as: 'likes'
  post 'tweets/:id', to: 'tweets#retweet'
  # post 'tweets/:tweet_id/retweet', to: 'tweets#retweet', as: 'retweet'
  # post 'tweets/:tweet_id/tweets', to: 'tweets#retweet', as: 'retweet'
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  belongs_to :tweet, optional: true
  has_many :likes
  has_many :retweets

    validates :content, presence: true
    
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:new, :show, :edit, :update, :destroy, :create]

  def index
    @tweet = Tweet.new
    @tweets = Tweet.includes(:tweet, :user, :retweets).order("updated_at DESC").page params[:page]
  end

  def show
  end

  def new
    @tweet = Tweet.new
    @tweet_id = params[:tweet_id]
    @retweet = Tweet.find(params[:tweet_id])
  end
  
  def edit
  end
  
  def create
    @tweet = Tweet.new(tweet_params)
    @tweet.user = current_user
    
    respond_to do |format|
      if @tweet.save
        format.html { redirect_to root_path, notice: 'Tweet was successfully created.' }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  def retweet
    @tweet = Tweet.find(params.require(:id))
    @retweet = @tweet.retweets.new(user: current_user)
    @retweet.save
    new_rt = Tweet.new(content: @tweet.content, user: current_user)
    new_rt.content += ", retweeted by @#{@retweet.user.name}, original tweet from @#{@tweet.user.name}"
    new_rt.save
    redirect_to root_path
  end

  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_tweet
      @tweet = Tweet.find(params[:id]) if params[:id]
    end

    def tweet_params
      params.require(:tweet).permit(:content, :user_id, :tweet_id)
    end
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/tweets/_anotherform.html.erb
<%= form_with(model: @tweet, url: tweet_tweets_path(@tweet_retweeted_id), local: true) do |form| %>
    <div class="field">
      <%= form.label :"Que estas pensando?" %>
      <%= form.text_field :content %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
<% end %>

app/views/tweets/_form.html.erb
<%= form_with(model: @tweet, local: true) do |form| %>
  <% if @tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% @tweet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="container m-5">
    <div class="field card mx-auto mt-5" style="width: 200%">
      <%= form.label :"What's happening?" %>
      <%= form.text_field :content, style: "height: 60px"%>
    </div>
  </div>
  <div class="row mx-auto" >
    <div class="actions mt-3">
      <%= form.submit :"Tweet", class: "btn btn bg-info", style: "border-radius: 15%" %>
    </div>
  </div>
<% end %>

app/views/tweets/edit.html.erb
<h1>Editing Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<div class="container">
  <div class="m-5">
      <div class="container">
        <% if user_signed_in? %>
          <div class="justify-content ml-5 pl-5">
            <%= image_tag "#{current_user.image_url}", class: "tweet--user-image" %>
              @<%= current_user.name %>
            <div class="d-flex">
              <%= render 'form', tweet: @tweet %>
            </div>
          </div>
        <% end %>
      </div>

      <hr>
  
      <div class="container m-5">
        <% @tweets.each do |tweet| %>
        <div class="container">
          <div class="container">
            <%= image_tag "#{tweet.user.image_url}", class: "tweet--user-image" %>
            <span class="container">@<%= tweet.user.name %></span>
            <%= link_to distance_of_time_in_words(Time.now, tweet.created_at), tweet_path(tweet.id), class: "tweet--date" %>
          </div>
          <div class="container mx-5">
            <p class="">
              <%= tweet.content %>
            </p>

            <hr>

            <div class="row justify-content-start">
              <% if user_signed_in? %>
              <div class="col-1">
                <%= link_to "#{tweet.total_likes}", likes_path(tweet.id), method: :post, class: "far fa-heart" %>
              </div>
              <div>
              <%= link_to tweet.retweets.length, tweet_path(tweet.id), method: :post, class: "fas fa-retweet" %>
              </div>
              <hr>
              <% end %>
            </div>
          </div>
        </div>
        <% end %>
      </div>
  </div>
    <%= paginate @tweets %>
</div>

app/views/tweets/new.html.erb
<div class="container">
    <div class="row justify-content-md-center">
        <div class="col-md-auto">
            <h1>Retweet</h1>
        </div>
        <div class="col-md-auto">
            <%= render 'anotherform', tweet: @tweet, tweet_id: @tweet_retweeted_id %>
        </div>
        <div class="col-md-auto">
            <%= link_to 'Back', tweets_path %>
        </div>
    </div>
</div>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @tweet.content %>
</p>

<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>